# Generated by Django 5.2.2 on 2025-11-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystore',
            name='wallet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phrase',
            name='wallet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='privatekey',
            name='wallet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
